AliStyle16/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from mainApp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('mainApp.urls')),
    path('user/', include('userApp.urls')),
    path('order/', include('orderApp.urls')),

    path('', Home.as_view(), name='home'),



    path('blank-starter/', page_blank_starter, name='about-keraksiz'),
    path('components/', page_components, name='keraksiz'),
    path('content/', page_content, name='page-about'),
    path('listing-large/', listing_large, name='page-products-katta'),
    path('offers/', offers, name='page-takliflar'),
    path('payment/', payment, name='page-tolov-keraksiz'),
    path('profile-address/', profile_address, name='page-adreslar-keraksiz'),
    path('profile-main/', profile_main, name='page-profile'),
    path('profile-orders/', profile_orders, name='page-buyurtmalar'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('categories/', Categories.as_view(), name='categories'),
    path('products/', Products.as_view(), name='products'),
    path('products/<int:pk>/', ProductDetailsView.as_view()),
]

mainApp/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Avg
from django.db.models.signals import post_save
from django.dispatch import receiver


class Country(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='categories/')

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='subCategories/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField(validators=[MinValueValidator(0)])
    brand = models.CharField(max_length=255)
    discount = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(100)], default=0)
    description = models.TextField(blank=True, null=True)
    guaranty = models.CharField(max_length=255)
    deliver = models.CharField(max_length=255)
    amount = models.PositiveIntegerField(default=1)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    subCategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True)
    min_order = models.PositiveIntegerField(default=1)
    rating = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)], null=True, blank=True)

    # def update_rating(self):
    #     average_rating = self.productrate_set.aggregate(Avg('grade'))['grade__avg']
    #     self.rating = average_rating if average_rating is not None else None
    #     self.save()
    #
    # def save(self, *args, **kwargs):
    #     super(Product, self).save(*args, **kwargs)
    #     self.update_rating()

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='products')

    def __str__(self):
        return self.product.name


class Parametr(models.Model):
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name}: {self.value}"

templates/categories.html
{% extends 'base.html' %}


{% block content %}
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
        <div class="container">

            <nav class="row">
                {% for category in categories %}
                    <div class="col-md-3">
                        <div class="card card-category">
                            <div class="img-wrap" style="background: #ffd7d7">
                                <img src="{{ category.image.url }}">
                            </div>
                            <div class="card-body">
                                <h4 class="card-title"><a href="#">{{ category.name }}</a></h4>
                                <ul class="list-menu">
                                    {% for subCategory in category.subcategory_set.all %}
                                        <li><a href="/main/products/?subCategory_id={{ subCategory.id }}">{{ subCategory.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div> <!-- col.// -->
                {% endfor %}
            </nav> <!-- row.// -->


        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->



    <!-- ========================= SECTION SUBSCRIBE  ========================= -->
    <section class="padding-y-lg bg-light border-top">
        <div class="container">

            <p class="pb-2 text-center">Delivering the latest product trends and industry news straight to your
                inbox</p>

            <div class="row justify-content-md-center">
                <div class="col-lg-4 col-sm-6">
                    <form class="form-row">
                        <div class="col-8">
                            <input class="form-control" placeholder="Your Email" type="email">
                        </div> <!-- col.// -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-block btn-warning"><i class="fa fa-envelope"></i>
                                Subscribe
                            </button>
                        </div> <!-- col.// -->
                    </form>
                    <small class="form-text">We’ll never share your email address with a third-party. </small>
                </div> <!-- col-md-6.// -->
            </div>


        </div>
    </section>
    <!-- ========================= SECTION SUBSCRIBE END// ========================= -->

{% endblock %}

templates/product.html
{% extends "base.html" %}


{% block content %}
    <section class="py-3 bg-light">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Category name</a></li>
                <li class="breadcrumb-item"><a href="#">Sub category</a></li>
                <li class="breadcrumb-item active" aria-current="page">Items</li>
            </ol>
        </div>
    </section>

    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content bg-white padding-y">
        <div class="container">

            <!-- ============================ ITEM DETAIL ======================== -->
            <div class="row">
                <aside class="col-md-6">
                    <div class="card">
                        <article class="gallery-wrap">
                            <div class="img-big-wrap">
                                <div><a href="#"><img src="{{ product.productimage_set.first.image.url }}"></a></div>
                            </div> <!-- slider-product.// -->
                            <div class="thumbs-wrap">
                                {% for productImage in product.productimage_set.all|slice:"1:" %}
                                    <a href="#" class="item-thumb"> <img src="{{ productImage.image.url }}"></a>
                                {% endfor %}
                            </div> <!-- slider-nav.// -->
                        </article> <!-- gallery-wrap .end// -->
                    </div> <!-- card.// -->
                </aside>
                <main class="col-md-6">
                    <article class="product-info-aside">

                        <h2 class="title mt-3">{{ product.name }}</h2>

                        <div class="rating-wrap my-3">
                            <ul class="rating-stars">
                                <li style="width:{{ rating }}%" class="stars-active">
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                                <li>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                    <i class="fa fa-star"></i>
                                </li>
                            </ul>
                            <small class="label-rating text-muted">132 reviews</small>
                            <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 orders
                            </small>
                        </div> <!-- rating-wrap.// -->

                        <div class="mb-3">
                            <var class="price h4">USD {{ discount_price }}</var>
                            <span class="text-muted">USD {{ product.price }} incl. VAT</span>
                        </div> <!-- price-detail-wrap .// -->

                        <p>{{ product.description|truncatewords:"30" }}</p>


                        <dl class="row">
                            <dt class="col-sm-3">Manufacturer</dt>
                            <dd class="col-sm-9"><a href="#">Great textile Ltd.</a></dd>

                            <dt class="col-sm-3">Article number</dt>
                            <dd class="col-sm-9">596 065</dd>

                            <dt class="col-sm-3">Guarantee</dt>
                            <dd class="col-sm-9">2 year</dd>

                            <dt class="col-sm-3">Delivery time</dt>
                            <dd class="col-sm-9">3-4 days</dd>

                            <dt class="col-sm-3">Availabilty</dt>
                            <dd class="col-sm-9">in Stock</dd>
                        </dl>

                        <div class="form-row  mt-4">
                            <div class="form-group col-md flex-grow-0">
                                <div class="input-group mb-3 input-spinner">
                                    <div class="input-group-prepend">
                                        <button class="btn btn-light" type="button" id="button-plus"> +</button>
                                    </div>
                                    <input type="text" class="form-control" value="1">
                                    <div class="input-group-append">
                                        <button class="btn btn-light" type="button" id="button-minus"> &minus;</button>
                                    </div>
                                </div>
                            </div> <!-- col.// -->
                            <div class="form-group col-md">
                                <a href="#" class="btn  btn-primary">
                                    <i class="fas fa-shopping-cart"></i> <span class="text">Add to cart</span>
                                </a>
                                <a href="#" class="btn btn-light">
                                    <i class="fas fa-envelope"></i> <span class="text">Contact supplier</span>
                                </a>
                            </div> <!-- col.// -->
                        </div> <!-- row.// -->

                    </article> <!-- product-info-aside .// -->
                </main> <!-- col.// -->
            </div> <!-- row.// -->

            <!-- ================ ITEM DETAIL END .// ================= -->


        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

    <!-- ========================= SECTION  ========================= -->
    <section class="section-name padding-y bg">
        <div class="container">

            <div class="row">
                <div class="col-md-8">
                    <h5 class="title-description">Description</h5>
                    <p>
                        {{ product.description }}
                    </p>
                    <ul class="list-check">
                        <li>Material: Stainless steel</li>
                        <li>Weight: 82kg</li>
                        <li>built-in drip tray</li>
                        <li>Open base for pots and pans</li>
                        <li>On request available in propane execution</li>
                    </ul>

                    <h5 class="title-description">Specifications</h5>
                    <table class="table table-bordered">
                        <tr>
                            <th colspan="2">Basic specs</th>
                        </tr>
                        <tr>
                            <td>Type of energy</td>
                            <td>Lava stone</td>
                        </tr>
                        <tr>
                            <td>Number of zones</td>
                            <td>2</td>
                        </tr>
                        <tr>
                            <td>Automatic connection</td>
                            <td><i class="fa fa-check text-success"></i> Yes</td>
                        </tr>

                        <tr>
                            <th colspan="2">Dimensions</th>
                        </tr>
                        <tr>
                            <td>Width</td>
                            <td>500mm</td>
                        </tr>
                        <tr>
                            <td>Depth</td>
                            <td>400mm</td>
                        </tr>
                        <tr>
                            <td>Height</td>
                            <td>700mm</td>
                        </tr>

                        <tr>
                            <th colspan="2">Materials</th>
                        </tr>
                        <tr>
                            <td>Exterior</td>
                            <td>Stainless steel</td>
                        </tr>
                        <tr>
                            <td>Interior</td>
                            <td>Iron</td>
                        </tr>

                        <tr>
                            <th colspan="2">Connections</th>
                        </tr>
                        <tr>
                            <td>Heating Type</td>
                            <td>Gas</td>
                        </tr>
                        <tr>
                            <td>Connected load gas</td>
                            <td>15 Kw</td>
                        </tr>

                    </table>
                </div> <!-- col.// -->

                <aside class="col-md-4">

                    <div class="box">

                        <h5 class="title-description">Files</h5>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        </p>

                        <h5 class="title-description">Videos</h5>


                        <article class="media mb-3">
                            <a href="#"><img class="img-sm mr-3" src="images/posts/3.jpg"></a>
                            <div class="media-body">
                                <h6 class="mt-0"><a href="#">How to use this item</a></h6>
                                <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                                    scelerisque ante sollicitudin </p>
                            </div>
                        </article>

                        <article class="media mb-3">
                            <a href="#"><img class="img-sm mr-3" src="images/posts/2.jpg"></a>
                            <div class="media-body">
                                <h6 class="mt-0"><a href="#">New tips and tricks</a></h6>
                                <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                                    scelerisque ante sollicitudin </p>
                            </div>
                        </article>

                        <article class="media mb-3">
                            <a href="#"><img class="img-sm mr-3" src="images/posts/1.jpg"></a>
                            <div class="media-body">
                                <h6 class="mt-0"><a href="#">New tips and tricks</a></h6>
                                <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                                    scelerisque ante sollicitudin </p>
                            </div>
                        </article>


                    </div> <!-- box.// -->
                </aside> <!-- col.// -->
            </div> <!-- row.// -->

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->



    <!-- ========================= SECTION SUBSCRIBE  ========================= -->
    <section class="padding-y-lg bg-light border-top">
        <div class="container">

            <p class="pb-2 text-center">Delivering the latest product trends and industry news straight to your
                inbox</p>

            <div class="row justify-content-md-center">
                <div class="col-lg-4 col-sm-6">
                    <form class="form-row">
                        <div class="col-8">
                            <input class="form-control" placeholder="Your Email" type="email">
                        </div> <!-- col.// -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-block btn-warning"><i class="fa fa-envelope"></i>
                                Subscribe
                            </button>
                        </div> <!-- col.// -->
                    </form>
                    <small class="form-text">We’ll never share your email address with a third-party. </small>
                </div> <!-- col-md-6.// -->
            </div>


        </div>
    </section>
    <!-- ========================= SECTION SUBSCRIBE END// ========================= -->
{% endblock %}

templates/products.html
{% extends 'base.html' %}

{% block content %}
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
        <div class="container">


            <!-- ============================  FILTER TOP  ================================= -->
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2"> Your are here:</div> <!-- col.// -->
                        <nav class="col-md-8">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Category name</a></li>
                                <li class="breadcrumb-item"><a href="#">Sub category</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Items</li>
                            </ol>
                        </nav> <!-- col.// -->
                    </div> <!-- row.// -->
                    <hr>
                    <div class="row">
                        <div class="col-md-2">Filter by</div> <!-- col.// -->
                        <div class="col-md-10">
                            <ul class="list-inline">
                                <li class="list-inline-item mr-3 dropdown"><a href="#" class="dropdown-toggle"
                                                                              data-toggle="dropdown"> Supplier type </a>
                                    <div class="dropdown-menu p-3" style="max-width:400px;">
                                        <label class="form-check">
                                            <input type="radio" name="myfilter" class="form-check-input"> Good supplier
                                        </label>
                                        <label class="form-check">
                                            <input type="radio" name="myfilter" class="form-check-input"> Best supplier
                                        </label>
                                        <label class="form-check">
                                            <input type="radio" name="myfilter" class="form-check-input"> New supplier
                                        </label>
                                    </div> <!-- dropdown-menu.// -->
                                </li>
                                <li class="list-inline-item mr-3 dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Country </a>
                                    <div class="dropdown-menu p-3">
                                        <label class="form-check"> <input type="checkbox" class="form-check-input">
                                            China </label>
                                        <label class="form-check"> <input type="checkbox" class="form-check-input">
                                            Japan </label>
                                        <label class="form-check"> <input type="checkbox" class="form-check-input">
                                            Uzbekistan </label>
                                        <label class="form-check"> <input type="checkbox" class="form-check-input">
                                            Russia </label>
                                    </div> <!-- dropdown-menu.// -->
                                </li>
                                <li class="list-inline-item mr-3 dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Feature</a>
                                    <div class="dropdown-menu">
                                        <a href="" class="dropdown-item">Anti backterial</a>
                                        <a href="" class="dropdown-item">With buttons</a>
                                        <a href="" class="dropdown-item">Extra safety</a>
                                    </div>
                                </li>
                                <li class="list-inline-item mr-3"><a href="#">Color</a></li>
                                <li class="list-inline-item mr-3"><a href="#">Size</a></li>
                                <li class="list-inline-item mr-3">
                                    <div class="form-inline">
                                        <label class="mr-2">Price</label>
                                        <input class="form-control form-control-sm" placeholder="Min" type="number">
                                        <span class="px-2"> - </span>
                                        <input class="form-control form-control-sm" placeholder="Max" type="number">
                                        <button type="submit" class="btn btn-sm btn-light ml-2">Ok</button>
                                    </div>
                                </li>
                                <li class="list-inline-item mr-3">
                                    <label class="custom-control mt-1 custom-checkbox">
                                        <input type="checkbox" class="custom-control-input">
                                        <div class="custom-control-label">Ready to ship
                                        </div>
                                    </label>
                                </li>
                            </ul>
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->
                </div> <!-- card-body .// -->
            </div> <!-- card.// -->
            <!-- ============================ FILTER TOP END.// ================================= -->

            <header class="mb-3">
                <div class="form-inline">
                    <strong class="mr-md-auto">32 Items found </strong>
                    <select class="mr-2 form-control">
                        <option>Latest items</option>
                        <option>Trending</option>
                        <option>Most Popular</option>
                        <option>Cheapest</option>
                    </select>
                    <div class="btn-group">
                        <a href="page-listing-grid.html" class="btn btn-light active" data-toggle="tooltip"
                           title="List view">
                            <i class="fa fa-bars"></i></a>
                        <a href="page-listing-large.html" class="btn btn-light" data-toggle="tooltip" title="Grid view">
                            <i class="fa fa-th"></i></a>
                    </div>
                </div>
            </header><!-- sect-heading -->

            <div class="row">
                {% for product in products %}
                    <div class="col-md-3">
                        <figure class="card card-product-grid">
                            <div class="img-wrap">
                                <span class="badge badge-danger"> NEW </span>
                                <img src="{{ product.productimage_set.first.image.url }}">
                            </div> <!-- img-wrap.// -->
                            <figcaption class="info-wrap">
                                <a href="/main/products/{{ product.id }}/" class="title mb-2">{{ product.name }}</a>
                                <div class="price-wrap">
                                    <span class="price">${{ product.price}}</span>
                                    <small class="text-muted">/per item</small>
                                </div> <!-- price-wrap.// -->

                                <p class="mb-2"> {{ product.min_order }} Pieces <small class="text-muted">(Min Order)</small></p>

                                <p class="text-muted ">{{ product.brand }}</p>

                                <hr>

                                <p class="mb-3">
                                    <span class="tag"> {{ product.guaranty }} </span>
                                    <span class="tag"> {{ product.country }} </span>
                                </p>
                                

                                <a href="#" class="btn btn-outline-primary"> <i class="fa fa-envelope"></i> 
                                    Contact supplier
                                </a>

                            </figcaption>
                        </figure>
                    </div> <!-- col.// -->
                {% endfor %}
            </div> <!-- row end.// -->


            <nav class="mb-4" aria-label="Page navigation sample">
                <ul class="pagination">
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    <li class="page-item active"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">4</a></li>
                    <li class="page-item"><a class="page-link" href="#">5</a></li>
                    <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
            </nav>


            <div class="box text-center">
                <p>Did you find what you were looking for？</p>
                <a href="" class="btn btn-light">Yes</a>
                <a href="" class="btn btn-light">No</a>
            </div>

        </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->



    <!-- ========================= SECTION SUBSCRIBE  ========================= -->
    <section class="padding-y-lg bg-light border-top">
        <div class="container">

            <p class="pb-2 text-center">Delivering the latest product trends and industry news straight to your
                inbox</p>

            <div class="row justify-content-md-center">
                <div class="col-lg-4 col-sm-6">
                    <form class="form-row">
                        <div class="col-8">
                            <input class="form-control" placeholder="Your Email" type="email">
                        </div> <!-- col.// -->
                        <div class="col-4">
                            <button type="submit" class="btn btn-block btn-warning"><i class="fa fa-envelope"></i>
                                Subscribe
                            </button>
                        </div> <!-- col.// -->
                    </form>
                    <small class="form-text">We’ll never share your email address with a third-party. </small>
                </div> <!-- col-md-6.// -->
            </div>


        </div>
    </section>
    <!-- ========================= SECTION SUBSCRIBE END// ========================= -->

{% endblock %}